"""Declarative metadata for Rush tools and externally discovered engines.

The catalog is deliberately dependency-free.  It describes Rush's own surface;
engine binaries remain optional and are resolved at runtime by ``run_engine``.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Literal

ToolCategory = Literal["quality", "security", "test", "workflow"]
EngineCapability = Literal["lint", "format", "test", "security", "metrics", "workflow"]
ToolMaturity = Literal[
    "real_adapter",
    "catalog_only",
    "guarded_placeholder",
    "direct_adapter_candidate",
    "importer",
    "feasibility_gated",
    "browser_runtime",
]
TOOL_MATURITY_VALUES: frozenset[ToolMaturity] = frozenset(
    {
        "real_adapter",
        "catalog_only",
        "guarded_placeholder",
        "direct_adapter_candidate",
        "importer",
        "feasibility_gated",
        "browser_runtime",
    }
)


@dataclass(frozen=True)
class ToolSpec:
    """Stable metadata shared by CLI help, MCP descriptions, and tests."""

    name: str
    category: ToolCategory
    description: str
    mcp_description: str
    engine_names: tuple[str, ...]
    supports_path: bool = True
    experimental: bool = False
    maturity: ToolMaturity = "catalog_only"


@dataclass(frozen=True)
class EngineSpec:
    """Install and routing metadata for an external engine binary."""

    name: str
    binary: str
    install_hint: str
    file_extensions: tuple[str, ...]
    project_markers: tuple[str, ...]
    capability: EngineCapability


TOOL_SPECS: dict[str, ToolSpec] = {
    "semantic-drift": ToolSpec(
        name="semantic-drift",
        category="test",
        description="Experimental browser-locator semantic drift detection.",
        mcp_description="Experimental semantic drift analysis; requires explicit browser and slow-run permission.",
        engine_names=("semantic-drift",),
        experimental=True,
    ),
    "review": ToolSpec(
        name="review",
        category="quality",
        description="Review code for deterministic heuristic quality signals.",
        mcp_description=(
            "Review <path> with deterministic heuristics. Returns {status, findings[], "
            "summary}; optional LLM and local Graft context use are explicit."
        ),
        engine_names=(),
    ),
    "lint": ToolSpec(
        name="lint",
        category="quality",
        description="Lint Python and JavaScript/TypeScript source files.",
        mcp_description=(
            "Lint Python/JS/TS files at <path>. Returns {status, findings[], summary}. "
            "Missing engines return status='skipped'."
        ),
        engine_names=("ruff", "eslint"),
    ),
    "format": ToolSpec(
        name="format",
        category="quality",
        description="Check formatting without silently rewriting files.",
        mcp_description=(
            "Check formatting at <path>. Returns {status, findings[], summary}. "
            "Missing engines return status='skipped'."
        ),
        engine_names=("ruff", "prettier"),
    ),
    "test": ToolSpec(
        name="test",
        category="test",
        description="Run the project test runner selected from project metadata.",
        mcp_description=(
            "Run tests at <path>. Returns {status, findings[], summary}. "
            "Missing engines return status='skipped'."
        ),
        engine_names=("pytest", "vitest"),
    ),
    "security": ToolSpec(
        name="security",
        category="security",
        description="Scan dependency manifests for known vulnerabilities.",
        mcp_description=(
            "Scan dependencies at <path>. Returns {status, findings[], summary}. "
            "Missing engines return status='skipped'."
        ),
        engine_names=("pip-audit", "npm-audit"),
    ),
    "typecheck": ToolSpec(
        name="typecheck",
        category="quality",
        description="Type-check Python and JavaScript/TypeScript source.",
        mcp_description="Type-check Python and JS/TS at <path>; missing mypy or tsc returns status='skipped'.",
        engine_names=("mypy", "tsc"),
    ),
    "dead": ToolSpec(
        name="dead",
        category="quality",
        description="Find unused Python and JavaScript/TypeScript code.",
        mcp_description=(
            "Find unused Python and JS/TS code at <path>; missing vulture or knip "
            "returns status='skipped'."
        ),
        engine_names=("vulture", "knip"),
    ),
    "complexity": ToolSpec(
        name="complexity",
        category="quality",
        description="Measure Python and JavaScript/TypeScript complexity.",
        mcp_description=(
            "Measure Python and JS/TS complexity at <path>; missing radon or jscpd "
            "returns status='skipped'."
        ),
        engine_names=("radon", "jscpd"),
    ),
    "slop": ToolSpec(
        name="slop",
        category="quality",
        description="Detect AI slop in Python and deterministic JS/TS noise signals.",
        mcp_description="Detect Python AI slop and deterministic JS/TS noise at <path>; missing sloppylint returns status='skipped'.",
        engine_names=("sloppylint",),
    ),
    "markdown": ToolSpec(
        name="markdown",
        category="quality",
        description="Check Markdown without rewriting files.",
        mcp_description="Check Markdown at <path> without rewriting; missing markdownlint-cli returns status='skipped'.",
        engine_names=("markdownlint-cli",),
    ),
    "actions": ToolSpec(
        "actions",
        "quality",
        "Check GitHub Actions workflows.",
        "Check Actions workflows at <path>; missing actionlint returns status='skipped'.",
        ("actionlint",),
    ),
    "yaml": ToolSpec(
        "yaml",
        "quality",
        "Check YAML and OpenAPI files with Rush-owned local rules.",
        "Check YAML at <path> with local rules only; missing spectral returns status='skipped'.",
        ("spectral",),
    ),
    "sql": ToolSpec(
        "sql",
        "quality",
        "Check SQL files with Rush-owned local configuration.",
        "Check SQL at <path> locally; missing sqlfluff returns status='skipped'.",
        ("sqlfluff",),
    ),
    "templates": ToolSpec(
        "templates",
        "quality",
        "Check HTML and template files.",
        "Check templates at <path>; missing djlint returns status='skipped'.",
        ("djlint",),
    ),
    "containerfile": ToolSpec(
        "containerfile",
        "quality",
        "Check Dockerfile and Containerfile sources.",
        "Check container files at <path>; missing hadolint returns status='skipped'.",
        ("hadolint",),
    ),
    "iac": ToolSpec(
        "iac",
        "quality",
        "Check Terraform infrastructure as code.",
        "Check Terraform at <path>; missing local engines return status='skipped'.",
        ("tflint", "checkov"),
    ),
    "secrets": ToolSpec(
        "secrets",
        "security",
        "Scan for secrets without exposing values.",
        "Scan for secrets at <path>; missing gitleaks returns status='skipped'.",
        ("gitleaks",),
    ),
    "sbom": ToolSpec(
        "sbom",
        "security",
        "Generate a safe SBOM artifact.",
        "Generate an SBOM at <path>; missing cdxgen returns status='skipped'.",
        ("cdxgen",),
    ),
    "coverage": ToolSpec(
        "coverage",
        "quality",
        "Collect configured coverage reports.",
        "Collect coverage at <path> without rewriting source files.",
        (),
    ),
    "codeql": ToolSpec(
        "codeql",
        "security",
        "Import a contained local CodeQL SARIF report.",
        "Import a contained CodeQL SARIF report at <path>; never runs CodeQL.",
        (),
    ),
    "mutation": ToolSpec(
        "mutation",
        "quality",
        "Run configured mutation tests.",
        "Run mutation tests only with --allow-slow.",
        (),
    ),
    "e2e": ToolSpec(
        "e2e",
        "quality",
        "Run configured end-to-end tests.",
        "Run E2E tests only with --allow-browser.",
        (),
    ),
    "pbt": ToolSpec(
        "pbt",
        "quality",
        "Run existing property-based tests.",
        "Run existing property tests without generating files.",
        (),
    ),
    "visual": ToolSpec(
        "visual",
        "quality",
        "Check visual baselines.",
        "Check visual baselines; updates require --accept.",
        (),
    ),
    "snapshot": ToolSpec(
        "snapshot",
        "quality",
        "Check snapshots.",
        "Check snapshots; updates require --accept.",
        (),
    ),
    "flaky": ToolSpec(
        "flaky",
        "quality",
        "Analyze historical flaky-test reports.",
        "Analyze reports without rerunning tests.",
        (),
    ),
    "fuzz": ToolSpec(
        "fuzz",
        "quality",
        "Run a declared fuzz target.",
        "Run fuzzing only with --allow-fuzz.",
        (),
    ),
    "load": ToolSpec(
        "load",
        "quality",
        "Run an explicit load scenario.",
        "Run load testing only with --allow-network.",
        (),
    ),
    "contract": ToolSpec(
        "contract",
        "quality",
        "Run existing contract suites.",
        "Run contract tests without provider deployment.",
        (),
    ),
    "commit-msg": ToolSpec(
        "commit-msg",
        "workflow",
        "Validate commit messages without rewriting history.",
        "Validate commit messages; it never rewrites Git history.",
        ("commitlint",),
    ),
    "ci": ToolSpec(
        "ci",
        "workflow",
        "Inspect local CI workflow configuration.",
        "Inspect local CI configuration without exposing credentials.",
        (),
    ),
    "release": ToolSpec(
        "release",
        "workflow",
        "Create a dry-run release plan.",
        "Create a dry-run release plan; publication requires confirmation.",
        (),
    ),
    "ai-eval": ToolSpec(
        "ai-eval",
        "security",
        "Evaluate LLM prompts, agent workflows, and safety guardrails.",
        "Evaluate LLM prompts, agent workflows, and safety guardrails; requires explicit permissions for live runs.",
        ("promptfoo", "garak", "deepeval", "guardrails"),
    ),
}


_TOOL_MATURITY: dict[str, ToolMaturity] = {
    "semantic-drift": "browser_runtime",
    "review": "real_adapter",
    "lint": "real_adapter",
    "format": "real_adapter",
    "test": "real_adapter",
    "security": "real_adapter",
    "typecheck": "real_adapter",
    "dead": "real_adapter",
    "complexity": "real_adapter",
    "slop": "real_adapter",
    "markdown": "real_adapter",
    "actions": "real_adapter",
    "yaml": "real_adapter",
    "sql": "real_adapter",
    "templates": "real_adapter",
    "containerfile": "real_adapter",
    "iac": "real_adapter",
    "secrets": "real_adapter",
    "sbom": "real_adapter",
    "coverage": "importer",
    "codeql": "importer",
    "mutation": "importer",
    "e2e": "real_adapter",
    "pbt": "importer",
    "visual": "real_adapter",
    "snapshot": "importer",
    "flaky": "importer",
    "fuzz": "importer",
    "load": "importer",
    "contract": "importer",
    "commit-msg": "real_adapter",
    "ci": "real_adapter",
    "release": "real_adapter",
    "ai-eval": "real_adapter",
}
if set(_TOOL_MATURITY) != set(TOOL_SPECS):
    raise RuntimeError("catalog maturity map must classify every tool exactly once")
TOOL_SPECS = {
    name: replace(spec, maturity=_TOOL_MATURITY[name])
    for name, spec in TOOL_SPECS.items()
}

# A `real_adapter` with an external engine requires a deterministic parser and
# invocation suite. Presence here is a promotion prerequisite, never a test
# substitute.
PARSER_FIXTURE_SUITES: dict[str, tuple[str, ...]] = {
    "lint": (
        "tests/test_ruff_reference.py",
        "tests/test_eslint_reference.py",
    ),
    "format": (
        "tests/test_ruff_reference.py",
        "tests/test_prettier_reference.py",
    ),
    "test": (
        "tests/test_pytest_reference.py",
        "tests/test_vitest_reference.py",
    ),
    "typecheck": (
        "tests/test_mypy_reference.py",
        "tests/test_tsc_reference.py",
    ),
    "dead": (
        "tests/test_vulture_reference.py",
        "tests/test_knip_reference.py",
    ),
    "complexity": (
        "tests/test_radon_reference.py",
        "tests/test_jscpd_reference.py",
    ),
    "slop": ("tests/test_sloppylint_reference.py",),
    "templates": ("tests/test_djlint_reference.py",),
    "commit-msg": ("tests/test_commitlint_reference.py",),
    "sbom": ("tests/test_cdxgen_reference.py",),
    "iac": (
        "tests/test_tflint_reference.py",
        "tests/test_checkov_reference.py",
    ),
    "containerfile": ("tests/test_hadolint_reference.py",),
    "actions": ("tests/test_actionlint_reference.py",),
    "markdown": ("tests/test_markdownlint_reference.py",),
    "yaml": ("tests/test_spectral_reference.py",),
    "sql": ("tests/test_sqlfluff_reference.py",),
    "secrets": ("tests/test_gitleaks_reference.py",),
    "security": (
        "tests/test_pip_audit_reference.py",
        "tests/test_npm_audit_reference.py",
        "tests/test_osv_reference.py",
    ),
    "e2e": ("tests/test_playwright_reference.py",),
    "visual": ("tests/test_browser_evidence.py",),
    "semantic-drift": (
        "tests/test_axe_reference.py",
        "tests/test_browser_evidence.py",
    ),
    "release": ("tests/test_cosign_reference.py",),
    "ai-eval": (
        "tests/test_promptfoo_reference.py",
        "tests/test_garak_reference.py",
        "tests/test_deepeval_reference.py",
        "tests/test_guardrails_reference.py",
    ),
}


ENGINE_SPECS: dict[str, EngineSpec] = {
    "ruff": EngineSpec(
        "ruff", "ruff", "pip install ruff", ("py", "pyi"), ("pyproject.toml",), "lint"
    ),
    "eslint": EngineSpec(
        "eslint",
        "eslint",
        "npm install -g eslint",
        ("js", "jsx", "mjs", "cjs", "ts", "tsx"),
        ("package.json",),
        "lint",
    ),
    "prettier": EngineSpec(
        "prettier",
        "prettier",
        "npm install -g prettier",
        ("js", "jsx", "mjs", "cjs", "ts", "tsx", "json", "yaml", "yml", "md"),
        ("package.json",),
        "format",
    ),
    "pytest": EngineSpec(
        "pytest",
        "pytest",
        "pip install pytest",
        ("py", "pyi"),
        ("pyproject.toml",),
        "test",
    ),
    "vitest": EngineSpec(
        "vitest",
        "vitest",
        "npm install -D vitest",
        ("js", "jsx", "ts", "tsx"),
        ("package.json",),
        "test",
    ),
    "pip-audit": EngineSpec(
        "pip-audit",
        "pip-audit",
        "pip install pip-audit",
        (),
        ("pyproject.toml", "requirements.txt"),
        "security",
    ),
    "npm-audit": EngineSpec(
        "npm-audit", "npm", "ships with npm", (), ("package.json",), "security"
    ),
    "osv-scanner": EngineSpec(
        "osv-scanner",
        "osv-scanner",
        "install osv-scanner",
        (),
        (
            "poetry.lock",
            "requirements.txt",
            "package-lock.json",
            "Cargo.lock",
            "go.sum",
        ),
        "security",
    ),
    "mypy": EngineSpec(
        "mypy", "mypy", "pip install mypy", ("py", "pyi"), ("pyproject.toml",), "lint"
    ),
    "tsc": EngineSpec(
        "tsc",
        "tsc",
        "npm install -D typescript",
        ("js", "jsx", "ts", "tsx"),
        ("package.json",),
        "lint",
    ),
    "vulture": EngineSpec(
        "vulture",
        "vulture",
        "pip install vulture",
        ("py", "pyi"),
        ("pyproject.toml",),
        "lint",
    ),
    "knip": EngineSpec(
        "knip",
        "knip",
        "npm install -D knip",
        ("js", "jsx", "ts", "tsx"),
        ("package.json",),
        "lint",
    ),
    "radon": EngineSpec(
        "radon",
        "radon",
        "pip install radon",
        ("py", "pyi"),
        ("pyproject.toml",),
        "metrics",
    ),
    "jscpd": EngineSpec(
        "jscpd",
        "jscpd",
        "npm install -D jscpd",
        ("js", "jsx", "ts", "tsx"),
        ("package.json",),
        "metrics",
    ),
    "sloppylint": EngineSpec(
        "sloppylint",
        "sloppylint",
        "pip install sloppylint",
        ("py", "pyi"),
        ("pyproject.toml",),
        "lint",
    ),
    "markdownlint-cli": EngineSpec(
        "markdownlint-cli",
        "markdownlint",
        "npm install -D markdownlint-cli",
        ("md", "mdx"),
        (),
        "lint",
    ),
    "actionlint": EngineSpec(
        "actionlint",
        "actionlint",
        "install actionlint",
        ("yml", "yaml"),
        (".github/workflows",),
        "lint",
    ),
    "spectral": EngineSpec(
        "spectral",
        "spectral",
        "npm install -D @stoplight/spectral-cli",
        ("yml", "yaml"),
        (),
        "lint",
    ),
    "sqlfluff": EngineSpec(
        "sqlfluff", "sqlfluff", "pip install sqlfluff", ("sql",), (), "lint"
    ),
    "djlint": EngineSpec(
        "djlint", "djlint", "pip install djlint", ("html", "jinja", "j2"), (), "lint"
    ),
    "hadolint": EngineSpec(
        "hadolint",
        "hadolint",
        "install hadolint",
        ("dockerfile", "containerfile"),
        (),
        "lint",
    ),
    "tflint": EngineSpec(
        "tflint", "tflint", "install tflint", ("tf",), (".terraform",), "lint"
    ),
    "checkov": EngineSpec(
        "checkov",
        "checkov",
        "pip install checkov",
        ("tf",),
        (".terraform",),
        "security",
    ),
    "gitleaks": EngineSpec(
        "gitleaks", "gitleaks", "install gitleaks", (), (), "security"
    ),
    "cdxgen": EngineSpec(
        "cdxgen", "cdxgen", "npm install -g @cyclonedx/cdxgen", (), (), "security"
    ),
    "commitlint": EngineSpec(
        "commitlint", "commitlint", "npm install -D @commitlint/cli", (), (), "workflow"
    ),
    "semantic-drift": EngineSpec(
        "semantic-drift",
        "semantic-drift",
        "configure a local .NET or Playwright semantic-drift target",
        (),
        (),
        "test",
    ),
    "semgrep": EngineSpec(
        "semgrep",
        "semgrep",
        "pip install semgrep",
        ("py", "js", "ts", "go", "java", "yaml", "json"),
        (),
        "security",
    ),
    "lychee": EngineSpec(
        "lychee",
        "lychee",
        "install lychee",
        ("md", "html"),
        (),
        "lint",
    ),
    "trivy": EngineSpec(
        "trivy",
        "trivy",
        "install trivy",
        (),
        (),
        "security",
    ),
    "grype": EngineSpec(
        "grype",
        "grype",
        "install grype",
        (),
        (),
        "security",
    ),
    "cosign": EngineSpec(
        "cosign",
        "cosign",
        "install cosign",
        (),
        (),
        "security",
    ),
    "kubeconform": EngineSpec(
        "kubeconform",
        "kubeconform",
        "install kubeconform",
        ("yaml", "yml"),
        (),
        "lint",
    ),
    "playwright": EngineSpec(
        "playwright",
        "playwright",
        "npm install -D @playwright/test",
        ("ts", "js"),
        (),
        "test",
    ),
    "axe": EngineSpec(
        "axe",
        "axe",
        "npm install -g @axe-core/cli",
        ("html",),
        (),
        "test",
    ),
    "promptfoo": EngineSpec(
        "promptfoo",
        "promptfoo",
        "npm install -g promptfoo",
        ("yaml", "yml", "json"),
        ("promptfooconfig.yaml",),
        "security",
    ),
    "garak": EngineSpec(
        "garak",
        "garak",
        "pip install garak",
        ("yaml", "yml", "py"),
        ("garak.yaml",),
        "security",
    ),
    "deepeval": EngineSpec(
        "deepeval",
        "deepeval",
        "pip install deepeval",
        ("py", "yaml", "yml"),
        ("deepeval.yaml",),
        "test",
    ),
    "guardrails": EngineSpec(
        "guardrails",
        "guardrails",
        "pip install guardrails-ai",
        ("co", "yml", "yaml"),
        (),
        "security",
    ),
    "bearer": EngineSpec(
        "bearer",
        "bearer",
        "install bearer",
        ("py", "js", "ts", "rb", "go", "java"),
        (),
        "security",
    ),
    "trufflehog": EngineSpec(
        "trufflehog",
        "trufflehog",
        "install trufflehog",
        (),
        (),
        "security",
    ),
    "horusec": EngineSpec(
        "horusec",
        "horusec",
        "install horusec",
        ("py", "js", "ts", "go", "java", "tf"),
        (),
        "security",
    ),
    "secretlint": EngineSpec(
        "secretlint",
        "secretlint",
        "npm install -g secretlint",
        (),
        (),
        "security",
    ),
    "detect-secrets": EngineSpec(
        "detect-secrets",
        "detect-secrets",
        "pip install detect-secrets",
        (),
        (".secrets.baseline",),
        "security",
    ),
    "scorecard": EngineSpec(
        "scorecard",
        "scorecard",
        "install scorecard",
        (),
        (".github/workflows",),
        "security",
    ),
    "scancode": EngineSpec(
        "scancode",
        "scancode",
        "pip install scancode-toolkit",
        (),
        (),
        "security",
    ),
    "slsa-verifier": EngineSpec(
        "slsa-verifier",
        "slsa-verifier",
        "install slsa-verifier",
        (),
        (),
        "security",
    ),
    "guac": EngineSpec(
        "guac",
        "guacone",
        "install guac",
        (),
        (),
        "security",
    ),
    "pip-licenses": EngineSpec(
        "pip-licenses",
        "pip-licenses",
        "pip install pip-licenses",
        (),
        ("pyproject.toml", "requirements.txt"),
        "security",
    ),
    "terrascan": EngineSpec(
        "terrascan",
        "terrascan",
        "install terrascan",
        ("tf", "yaml", "yml", "json"),
        (),
        "security",
    ),
    "kube-score": EngineSpec(
        "kube-score",
        "kube-score",
        "install kube-score",
        ("yaml", "yml", "json"),
        (),
        "lint",
    ),
    "conftest": EngineSpec(
        "conftest",
        "conftest",
        "install conftest",
        ("yaml", "yml", "json", "tf"),
        (),
        "security",
    ),
    "polaris": EngineSpec(
        "polaris",
        "polaris",
        "install polaris",
        ("yaml", "yml", "json"),
        (),
        "security",
    ),
    "kube-linter": EngineSpec(
        "kube-linter",
        "kube-linter",
        "install kube-linter",
        ("yaml", "yml", "json"),
        (),
        "lint",
    ),
    "schemathesis": EngineSpec(
        "schemathesis",
        "schemathesis",
        "pip install schemathesis",
        ("json", "yaml", "yml"),
        (),
        "test",
    ),
    "zally": EngineSpec(
        "zally",
        "zally",
        "install zally",
        ("json", "yaml", "yml"),
        (),
        "lint",
    ),
    "graphql-inspector": EngineSpec(
        "graphql-inspector",
        "graphql-inspector",
        "npm install -g @graphql-inspector/cli",
        ("graphql", "gql", "json"),
        (),
        "lint",
    ),
    "cherrybomb": EngineSpec(
        "cherrybomb",
        "cherrybomb",
        "install cherrybomb",
        ("json", "yaml", "yml"),
        (),
        "security",
    ),
    "newman": EngineSpec(
        "newman",
        "newman",
        "npm install -g newman",
        ("json",),
        (),
        "test",
    ),
    "depcruise": EngineSpec(
        "depcruise",
        "depcruise",
        "npm install -D dependency-cruiser",
        ("js", "jsx", "ts", "tsx"),
        ("package.json",),
        "metrics",
    ),
    "refurb": EngineSpec(
        "refurb",
        "refurb",
        "pip install refurb",
        ("py", "pyi"),
        ("pyproject.toml",),
        "lint",
    ),
    "biome": EngineSpec(
        "biome",
        "biome",
        "npm install -D @biomejs/biome",
        ("js", "jsx", "ts", "tsx", "json"),
        ("package.json", "biome.json"),
        "lint",
    ),
    "scaphandre": EngineSpec(
        "scaphandre",
        "scaphandre",
        "install scaphandre",
        (),
        (),
        "metrics",
    ),
    "fawltydeps": EngineSpec(
        "fawltydeps",
        "fawltydeps",
        "pip install fawltydeps",
        ("py", "toml", "txt"),
        ("pyproject.toml", "requirements.txt"),
        "lint",
    ),
    "ts-prune": EngineSpec(
        "ts-prune",
        "ts-prune",
        "npm install -D ts-prune",
        ("ts", "tsx"),
        ("tsconfig.json", "package.json"),
        "lint",
    ),
    "pa11y": EngineSpec(
        "pa11y",
        "pa11y",
        "npm install -g pa11y",
        ("html", "htm"),
        (),
        "security",
    ),
    "html-validate": EngineSpec(
        "html-validate",
        "html-validate",
        "npm install -D html-validate",
        ("html", "htm", "vue", "svelte"),
        (),
        "lint",
    ),
    "lighthouse": EngineSpec(
        "lighthouse",
        "lighthouse",
        "npm install -g lighthouse",
        (),
        (),
        "metrics",
    ),
    "zap": EngineSpec(
        "zap",
        "zap-cli",
        "pip install zapcli",
        (),
        (),
        "security",
    ),
    "deadfinder": EngineSpec(
        "deadfinder",
        "deadfinder",
        "install deadfinder",
        (),
        (),
        "security",
    ),
    "blc": EngineSpec(
        "blc",
        "blc",
        "npm install -g broken-link-checker",
        (),
        (),
        "lint",
    ),
    "pagespeed": EngineSpec(
        "pagespeed",
        "pagespeed-insights",
        "npm install -g psi",
        (),
        (),
        "metrics",
    ),
    "stryker": EngineSpec(
        "stryker",
        "stryker",
        "npm install -D @stryker-mutator/core",
        ("js", "jsx", "ts", "tsx", "cs"),
        ("package.json",),
        "test",
    ),
    "cosmic-ray": EngineSpec(
        "cosmic-ray",
        "cosmic-ray",
        "pip install cosmic-ray",
        ("py",),
        ("pyproject.toml",),
        "test",
    ),
    "infection": EngineSpec(
        "infection",
        "infection",
        "composer require --dev infection/infection",
        ("php",),
        ("composer.json",),
        "test",
    ),
    "pitest": EngineSpec(
        "pitest",
        "mvn",
        "install pitest",
        ("java", "kt"),
        ("pom.xml",),
        "test",
    ),
    "cargo-mutants": EngineSpec(
        "cargo-mutants",
        "cargo-mutants",
        "cargo install cargo-mutants",
        ("rs",),
        ("Cargo.toml",),
        "test",
    ),
    "lost-pixel": EngineSpec(
        "lost-pixel",
        "lost-pixel",
        "npm install -D lost-pixel",
        (),
        ("package.json",),
        "test",
    ),
    "backstop": EngineSpec(
        "backstop",
        "backstop",
        "npm install -g backstopjs",
        (),
        ("package.json",),
        "test",
    ),
    "stylelint": EngineSpec(
        "stylelint",
        "stylelint",
        "npm install -D stylelint",
        ("css", "scss", "sass", "less"),
        ("package.json",),
        "lint",
    ),
    "a11ywatch": EngineSpec(
        "a11ywatch",
        "a11ywatch",
        "npm install -g a11ywatch-cli",
        (),
        (),
        "security",
    ),
    "squoosh": EngineSpec(
        "squoosh",
        "squoosh-cli",
        "npm install -g @squoosh/cli",
        ("png", "jpg", "jpeg", "webp", "avif"),
        (),
        "format",
    ),
    "critical": EngineSpec(
        "critical",
        "critical",
        "npm install -g critical",
        ("html", "htm"),
        (),
        "format",
    ),
    "font-spider": EngineSpec(
        "font-spider",
        "font-spider",
        "npm install -g font-spider",
        ("html", "htm"),
        (),
        "format",
    ),
    "ast-grep": EngineSpec(
        "ast-grep",
        "ast-grep",
        "npm install -g @ast-grep/cli",
        (
            "py",
            "js",
            "jsx",
            "ts",
            "tsx",
            "rs",
            "go",
            "c",
            "cpp",
            "java",
            "html",
            "css",
        ),
        (),
        "lint",
    ),
    "flake8-bugbear": EngineSpec(
        "flake8-bugbear",
        "flake8",
        "pip install flake8-bugbear",
        ("py", "pyi"),
        ("pyproject.toml",),
        "lint",
    ),
    "megalinter": EngineSpec(
        "megalinter",
        "megalinter",
        "install megalinter",
        (),
        (),
        "lint",
    ),
    "comby": EngineSpec(
        "comby",
        "comby",
        "install comby",
        ("py", "js", "jsx", "ts", "tsx", "go", "rs", "c", "cpp", "java"),
        (),
        "lint",
    ),
    "atlas": EngineSpec(
        "atlas",
        "atlas",
        "install atlas",
        ("sql", "hcl"),
        (),
        "lint",
    ),
    "squawk": EngineSpec(
        "squawk",
        "squawk",
        "npm install -g squawk-cli",
        ("sql",),
        (),
        "lint",
    ),
    "prisma-lint": EngineSpec(
        "prisma-lint",
        "prisma-lint",
        "npm install -D prisma-lint",
        ("prisma",),
        (),
        "lint",
    ),
    "vale": EngineSpec(
        "vale",
        "vale",
        "install vale",
        ("md", "mdx", "rst", "adoc", "html", "txt"),
        (),
        "lint",
    ),
    "cspell": EngineSpec(
        "cspell",
        "cspell",
        "npm install -g cspell",
        (
            "py",
            "js",
            "jsx",
            "ts",
            "tsx",
            "md",
            "json",
            "yaml",
            "yml",
            "html",
            "css",
        ),
        (),
        "lint",
    ),
    "alex": EngineSpec(
        "alex",
        "alex",
        "npm install -g alex",
        ("md", "mdx", "txt", "html"),
        (),
        "lint",
    ),
    "readability": EngineSpec(
        "readability",
        "readability-cli",
        "npm install -g readability-cli",
        ("md", "mdx", "txt", "html"),
        (),
        "metrics",
    ),
    "redpen": EngineSpec(
        "redpen",
        "redpen",
        "install redpen",
        ("md", "txt", "adoc"),
        (),
        "lint",
    ),
    "no-jargon": EngineSpec(
        "no-jargon",
        "no-jargon",
        "npm install -g no-jargon",
        ("md", "mdx", "txt", "rst"),
        (),
        "lint",
    ),
    "markdown-unfluff": EngineSpec(
        "markdown-unfluff",
        "markdown-unfluff",
        "pip install markdown-unfluff",
        ("md", "mdx", "markdown"),
        (),
        "lint",
    ),
    "memray": EngineSpec(
        "memray",
        "memray",
        "pip install memray",
        ("py",),
        ("pyproject.toml",),
        "metrics",
    ),
    "statoscope": EngineSpec(
        "statoscope",
        "statoscope",
        "npm install -D @statoscope/cli",
        ("json",),
        (),
        "metrics",
    ),
    "bloaty": EngineSpec(
        "bloaty",
        "bloaty",
        "install bloaty",
        ("exe", "dll", "so", "dylib", "wasm"),
        (),
        "metrics",
    ),
    "buf": EngineSpec(
        "buf",
        "buf",
        "install buf",
        ("proto",),
        (),
        "lint",
    ),
    "dockle": EngineSpec(
        "dockle",
        "dockle",
        "install dockle",
        ("dockerfile", "containerfile"),
        (),
        "security",
    ),
    "wasm-tools": EngineSpec(
        "wasm-tools",
        "wasm-tools",
        "install wasm-tools",
        ("wasm", "wat"),
        (),
        "lint",
    ),
    "pyclean": EngineSpec(
        "pyclean",
        "pyclean",
        "pip install pyclean",
        (),
        (),
        "format",
    ),
    "diff-cover": EngineSpec(
        "diff-cover",
        "diff-cover",
        "pip install diff-cover",
        ("xml", "json"),
        (),
        "metrics",
    ),
    "git-guard": EngineSpec(
        "git-guard",
        "git",
        "ships with git",
        (),
        (),
        "lint",
    ),
    "semantic-release": EngineSpec(
        "semantic-release",
        "semantic-release",
        "npm install -g semantic-release",
        (),
        (),
        "workflow",
    ),
    "pr-agent": EngineSpec(
        "pr-agent",
        "pr-agent",
        "pip install pr-agent",
        (),
        (),
        "workflow",
    ),
    "safe-env": EngineSpec(
        "safe-env",
        "safe-env",
        "npm install -g safe-env",
        ("env", "example", "sample", "dist"),
        (),
        "security",
    ),
    "wait-on": EngineSpec(
        "wait-on",
        "wait-on",
        "npm install -g wait-on",
        (),
        (),
        "workflow",
    ),
    "ncu": EngineSpec(
        "ncu",
        "ncu",
        "npm install -g npm-check-updates",
        ("json",),
        ("package.json",),
        "workflow",
    ),
}


__all__ = [
    "ENGINE_SPECS",
    "PARSER_FIXTURE_SUITES",
    "TOOL_MATURITY_VALUES",
    "TOOL_SPECS",
    "EngineSpec",
    "ToolMaturity",
    "ToolSpec",
]
