"""Detect Python AI slop and deterministic JavaScript/TypeScript noise signals."""

from __future__ import annotations

from pathlib import Path

from .base import ToolFn, ToolResult
from .common import elapsed_ms, now_ms, run_engine
from .routing import collect_files


class SlopTool(ToolFn):
    name = "slop"

    @property
    def mcp_description(self) -> str:
        return "Detect Python AI slop and deterministic JS/TS noise at <path>; missing sloppylint returns status='skipped' when no JS/TS fallback applies."

    def __call__(self, path: Path) -> ToolResult:
        return self.run(path)

    def run(self, path: Path, *, config=None) -> ToolResult:
        from ..engines import ENGINES

        start = now_ms()
        python_files = collect_files(path, {"py", "pyi"})
        js_files = collect_files(path, {"js", "jsx", "mjs", "cjs", "ts", "tsx"})
        findings = []
        if js_files:
            for file in js_files:
                for number, line in enumerate(
                    file.read_text(encoding="utf-8", errors="ignore").splitlines(), 1
                ):
                    if "TODO: AI" in line or "generated by ai" in line.lower():
                        findings.append(
                            {
                                "path": str(file),
                                "line": number,
                                "rule": "rush-ai-marker",
                                "severity": "warn",
                                "message": "AI-generated marker in source",
                            }
                        )
        if python_files:
            result = run_engine(
                ENGINES["sloppylint"],
                path,
                [str(file) for file in python_files],
                tool_name=self.name,
            )
            result["findings"] = sorted(
                [*result["findings"], *findings],
                key=lambda item: (
                    item.get("path", ""),
                    item.get("line") or 0,
                    item.get("rule", ""),
                ),
            )
            if findings and result["status"] == "skipped":
                result["engine"] = "rush"
                result["status"] = "warn"
                result["summary"] = f"rush heuristic: {len(findings)} issue(s)"
            result["duration_ms"] = elapsed_ms(start)
            return result
        if findings:
            return ToolResult(
                tool=self.name,
                engine="rush",
                engine_version=None,
                status="warn",
                duration_ms=elapsed_ms(start),
                summary=f"rush heuristic: {len(findings)} issue(s)",
                findings=findings,
                raw=None,
            )
        return ToolResult(
            tool=self.name,
            engine=None,
            engine_version=None,
            status="skipped",
            duration_ms=elapsed_ms(start),
            summary=f"slop: no supported source files found under {path}",
            findings=[],
            raw=None,
        )
