"""Offline OpenAPI to TypeScript interface generator."""

from __future__ import annotations

import json
from pathlib import Path


class TypeScriptContractGenerator:
    """Generates TypeScript interfaces directly from OpenAPI schema component definitions."""

    @staticmethod
    def generate_interfaces(openapi_json: str) -> str:
        data = json.loads(openapi_json)
        schemas = data.get("components", {}).get("schemas", {})
        ts_lines = ["// Auto-generated by Rush v0.2.0. Do not edit manually.", ""]

        for schema_name, schema_body in schemas.items():
            ts_lines.append(f"export interface {schema_name} {{")
            properties = schema_body.get("properties", {})
            required = schema_body.get("required", [])

            for prop_name, prop_meta in properties.items():
                is_req = prop_name in required
                optional_marker = "" if is_req else "?"
                p_type = prop_meta.get("type", "any")

                ts_type = "any"
                if p_type == "string":
                    ts_type = "string"
                elif p_type in ("integer", "number"):
                    ts_type = "number"
                elif p_type == "boolean":
                    ts_type = "boolean"
                elif p_type == "array":
                    ts_type = "any[]"

                ts_lines.append(f"  {prop_name}{optional_marker}: {ts_type};")

            ts_lines.append("}\n")

        return "\n".join(ts_lines)
